### PR TITLE
Make sure Microsoft.Storage is registered before checking name availability

### LINKED ISSUE #55: make prepare on a new sub register storage account resource provider
When running the prepare command on a brand new subscirption you will get the following error:
```
2022/10/14 09:17:23 azure.go:96: tf-prepare: "msg"="client.CheckNameAvailability" "error"="POST https://management.azure.com/subscriptions/0000-0000-00000-0000-000/providers/Microsoft.Storage/checkNameAvailability\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 Not Found\nERROR CODE: SubscriptionNotFound\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"SubscriptionNotFound\",\n    \"message\": \"Subscription 0000-0000-00000-0000-000 was not found.\"\n  }\n}\n--------------------------------------------------------------------------------\n"
```

Due to MS reasons you need to register a resource provider before trying to run API calls towards Az storage accounts.

This is done automatically by the portal, cli or terraform.
But our prepare command don't try to create something, all it does is to run a check if the name exist.

So when running `az storage account check-name --name sadevwetfstate` you will get 

```
(SubscriptionNotFound) Subscription 0000-0000-00000-0000-000 was not found.
Code: SubscriptionNotFound
Message: Subscription 0000-0000-00000-0000-000  was not found.
```
Which is a really bad error but it is what it is.

To solve the issue you have to manually register Microsoft.Storage Subscirption -> Resource Providers 

image

You will be able to run the prepare command without any issues.

Instead of doing this manually, we should do this through the API during the prepare command.

### PR DESCRIPTION
**Pull request by simongottschlag**
Fixes #55 

This PR introduces a change that checks that the Resource Provider `Microsoft.Storage` is registered before trying to check the name availability.

### CODE REVIEW

**Review by nissessenap — APPROVED** [review]

File: docker/go-tf-prepare/pkg/azure/azure.go [hunk 1]
```diff
@@ -142,6 +147,64 @@ func CreateStorageAccount(ctx context.Context, cred azcore.TokenCredential, conf
...
+		if err != nil {
+			log.Error(err, "client.Get")
+			return err
+		}
+		currentRegistrationState = *res.RegistrationState
+		if currentRegistrationState == "Registered" {
+			log.Info("Azure Resource Provider registered", "resourceProviderNamespace", resourceProviderNamespace, "registrationState", currentRegistrationState)
+			return nil
+		}
+		time.Sleep(time.Duration(i*5) * time.Second)
```
Comment (bittrance) [inline docker/go-tf-prepare/pkg/azure/azure.go:209]: You should probably bail if status != "Registering" or whatever it normally is while it is pondering. The registration can be minutes long, so you might want to print some feedback.

**Review by bittrance — APPROVED** [review]

File: docker/go-tf-prepare/pkg/azure/azure.go (hunk 1 above)
Comment (simongottschlag) [reply docker/go-tf-prepare/pkg/azure/azure.go:209]: @bittrance fixed!
